### ISSUE TITLE
error when loading the pretrained model

### ISSUE THREAD

**Issue by TomSheng21** [wasidennis/AdaptSegNet#101]
when I load the pretrained model which is downloaded from 

http://vllab.ucmerced.edu/ytsai/CVPR18/DeepLab_resnet_pretrained_init-f81d91e8.pth

then `torch.load()` will report an error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/xxx/software/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data1/xxx/software/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/serialization.py", line 779, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 278891 more bytes. The file might be corrupted.
```

Is the online model incomplete？

**Comment by HuanyuYang02** [comment]
Hi， I got the similar problem. Could you let me know if you found any solution?Thank you.
