### ISSUE TITLE
Error on pytorch 0.4

### ISSUE THREAD

**Issue by redhat12345** [wasidennis/AdaptSegNet#40]
I am trying to run the code with pytorch 0.4 but got the following error. How can I solve the problem? Thanks in advance.

Downloading: "http://vllab.ucmerced.edu/ytsai/CVPR18/DeepLab_resnet_pretrained_init-f81d91e8.pth" to /home/redhat/.torch/models/DeepLab_resnet_pretrained_init-f81d91e8.pth
Traceback (most recent call last):
  File "train_gta2cityscapes_multi.py", line 422, in <module>
    main()
  File "train_gta2cityscapes_multi.py", line 178, in main
    saved_state_dict = model_zoo.load_url(args.restore_from)
  File "/home/redhat/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 65, in load_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/redhat/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 72, in _download_url_to_file
    file_size = int(u.headers["Content-Length"])
  File "/home/redhat/anaconda3/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

**Comment by wasidennis** [comment]
One quick solution is to directly download the pre-trained model from the link offline, and put the model path to load it for training.
