### ISSUE TITLE
the size

### ISSUE THREAD

**Issue by FrancisLeon** [wasidennis/AdaptSegNet#7]
Sorry to trouble,
I sufferred from such an issue,
when I try to run the code (multi or single), I modify the input_size = '1280,720' to input_size = '1280,512', while the in fact images size of GTA is 1914,1052, otherwise, this error may happen:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
Traceback (most recent call last):
  File "train_gta2cityscapes_multi.py", line 411, in <module>
    main()
  File "train_gta2cityscapes_multi.py", line 201, in main
    model.cuda(args.gpu)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25
```
Also, I modified the loss_adv_target1.data.cpu().numpy()[0] to loss_adv_target1.data.cpu().numpy(), since it showed too many indices

And after I modified the input_size as '1280,512' and finished training, and performed the evaluation:
python evaluate_cityscapes.py --restore-from ./snapshots/GTA2Cityscapes_single/GTA5_250000.pth
this issue happened:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memoryTraceback (most recent call last):
  File "evaluate_cityscapes.py", line 134, in <module>
    main()
  File "evaluate_cityscapes.py", line 100, in main
    saved_state_dict = torch.load(args.restore_from)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 228, in __enter__
    _lazy_init()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25
```
So, I wonder whether my input_size setting is wrong.
Thanks

**Comment by hfslyc** [comment]
Hi,

Thanks for interested in our work. For the input size, I think you need a GPU with larger memory size to test our model (at least 12GB). If you use different "input_size", I'm afraid that you won't get the correct results. Just like you mentioned, since GTA5 image size is large, we downsize the image in order to train it with a 12GB GPU.

For the second issue, I assume you are using pytorch 0.4 where they modify the single element output. Your modification should be correct

**Comment by FrancisLeon** [comment]
Thanks for your reply and kindness.
In fact, I downsize the as '1280,512', though it may not be correct, it's still wired I could not evaluate but I could train it. So, you may mean even though I could train it, but the evaluation require larger memory size as yours? In fact, I found the size of trained result GTA5_250000.pth is same as GTA2Cityscapes_multi-ed35151c.pth --- 178.0 MB.  Thanks.

**Comment by FrancisLeon** [comment]
Thanks for your response. As you mentioned, you have to downsize the image, so the '1280,720' is the limit of your GPU?

**Comment by FrancisLeon** [comment]
Thanks for your reply and kindness. I figure it out.
